### PR TITLE
Add PSR-7 compatible responses

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
This adds PSR-7 compatible responses to our Application layer.

There is one b/c breaking change - getBody no longer accepts toArray as a parameter as it stored in a stream object now rather than as an array of strings

### CODE REVIEW

**Comment by mbabker** [comment]
Two B/C breaks: You're changing the constructor signature to require a Response object (and therefore making it the first parameter in the signature).

Get the tests wired up and I'm good with this.

**Comment by wilsonge** [comment]
Ahh yeah I meant to say. Do we want that b/c break. Given because of creating the stream we have to hard depend on Diactoros, we could make it optional and create an empty response object if one isn't supplied?

**Comment by mbabker** [comment]
What value is there in mandating a Response object be added?

Depending on Diactoros isn't an issue as that is all internals based stuff.  Our response object API (the getter and setter for it) should support PSR-7 in full but beyond that the rest is internal implementation details.

**Comment by mbabker** [comment]
Remember the HTTP package is dependent on Diactoros but it is serving an object that is compatible with all PSR-7 implementations.  So using a specific implementation of the standard for the internals isn't a problem as long as it works correctly.

**Comment by wilsonge** [comment]
At the time it was just based around not fully depending on Diactoros. But as soon as I came to stream creation it became an issue (like in http) - so it's not a big deal to make it an optional dependency other than more concrete uses of Diactoros

**Comment by mbabker** [comment]
Diactoros has to be a required dependency otherwise you have to make all the response related methods in the application abstract.

**Comment by wilsonge** [comment]
Response is now optional. I've gone with the base Response class rather than one of the Diactoros format aware classes...

**Comment by wilsonge** [comment]
OK This fixes the tests. But I'm very unsure of my response object replacing the mock (I've used a easy TextResponse then removed the content type to make it not have the free header it builds in the constructor).

Also I think `appendBody` can also be more smart than I've made it will work on that tomorrow. If the stream is writeable it should be able to keep writing to the existing stream rather than trying to create a new one by default

**Comment by wilsonge** [comment]
@mbabker Could you please
1) Review the way I'm setting up the "mock responses" in the unit tests (I feel like I shouldn't have to set up a Zend Object but that's what I've ended up doing to get header and body information out)
2) Help with changing the application `Mocker.php` tests (https://github.com/joomla-framework/application/blob/2.0-dev/Tests/Mocker.php). I'm really not sure what the best thing to do there is...

**Comment by mbabker** [comment]
Can we just get rid of the mocker?  What value is it really adding at this point?

**Comment by wilsonge** [comment]
https://github.com/joomla-framework/application/tree/2.0-dev#mocking-the-application-package Apparently it's for complicated mocking

**Comment by mbabker** [comment]
I know what the intent was when it was created, but in 2017 is it feasible to still have such an object (that's not even "real" API and not something really included in the package) or is it more feasible to expect downstream implementations to set up mocks through the PHPUnit API (or whatever tool they prefer)?

**Comment by wilsonge** [comment]
Pass. I've not had to write said complicated unit tests that require this because I'm normally testing one method at a time....

**Comment by wilsonge** [comment]
OK separate PR to remove the mocker https://github.com/joomla-framework/application/pull/66

**Pull request merged**
