### PR TITLE
adds bingbot and Edge to the test list

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for adds bingbot and Edge to the test list

### Summary of Changes
adds bingbot and Edge to the test list
fixes the version detection and engine detection for Edge

### Testing Instructions
Code review Travis tests pass

### Documentation Changes Required
none

### CODE REVIEW

**Comment by photodude** [comment]
@mbabker This adds tests and corrects the version detection and engine detection for Edge. (sorry, I didn't include this in the other PR)

**Comment by photodude** [comment]
@mbabker any thoughts on a 1.6.1 or 1.7.0 release so the CMS can possibly have these fixes in 3.7.0 ?

**Comment by mbabker** [comment]
If I remember I can tag something in the next few days since there's a few changes in the queue.  I really don't like tagging versions with only one or two small things unless it's fixing a bigger issue so I usually let them pile up.

**Comment by photodude** [comment]
Sounds like a plan.

**Comment by photodude** [comment]
@mbabker ping to remind for tagging a new release

**Comment by mbabker** [comment]
I'm blocking time tomorrow to do some Framework maintenance work (tagging items, updating API docs, updating the CMS dependencies, try to touch on some of my todo items for the site).

**Pull request merged**
